### ISSUE TITLE
Cannot find module '@babel/core' when running npm start after clonning

### ISSUE THREAD

**Issue by mustafawm** [reactjs/react-tabs#222]
Hello,

I just cloned the repo and installed dependencies then `npm start`ed. I'm getting the following error

```
Module build failed: Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mustafa/Code/SandBox/react-tabs/node_modules/babel-core/index.js:2:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mustafa/Code/SandBox/react-tabs/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
 @ multi (webpack)-dev-server/client?http://localhost:7878 ./app.js
```

i event installed babel-core again but still no luck

**Comment by rubangarmon** [comment]
Did you resolve this problem? I have the same problem.

**Comment by danez** [comment]
This should work fine. Just ensure you use the latest version of yarn.

**Comment by rubangarmon** [comment]
I'm using the most recent version of npm v5.6.0

This is the error:

```
c:\test-dev3\name_app>npm run start
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'run',
npm verb cli   'start' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle name_app@1.0.0~prestart: name_app@1.0.0
npm info lifecycle name_app@1.0.0~start: name_app@1.0.0

> name_app@1.0.0 start c:\test-dev3\name_app
> webpack-dev-server --config webpack/config/dev.config.js --open

Project is running at http://localhost:8080/
webpack output is served from /assets
Content not from webpack is served from ./dist
404s will fallback to /index.html
webpack: wait until bundle finished: /assets/bundle.js
Hash: e5afd651a3e015181387
Version: webpack 3.11.0
Time: 1630ms
                        Asset       Size  Chunks                    Chunk Names
images/login-background-8.jpg     140 kB          [emitted]
                    bundle.js     329 kB       0  [emitted]  [big]  main
images/login-background-2.jpg     294 kB          [emitted]  [big]
images/login-background-4.jpg     428 kB          [emitted]  [big]
images/login-background-6.jpg     243 kB          [emitted]
                bundle.js.map     390 kB       0  [emitted]         main
images/login-background-3.jpg    1.41 MB          [emitted]  [big]
images/login-background-5.jpg    1.41 MB          [emitted]  [big]
images/login-background-7.jpg    1.71 MB          [emitted]  [big]
images/login-background-1.jpg     2.6 MB          [emitted]  [big]
                ../index.html  748 bytes          [emitted]
  [35] multi (webpack)-dev-server/client?http://localhost:8080 ./src/client-app/index.js 40 bytes {0} [built]
  [36] (webpack)-dev-server/client?http://localhost:8080 7.23 kB {0} [built]
  [37] ./node_modules/url/url.js 23.3 kB {0} [built]
  [39] ./node_modules/url/util.js 314 bytes {0} [built]
  [40] ./node_modules/querystring-es3/index.js 127 bytes {0} [built]
  [43] ./node_modules/strip-ansi/index.js 161 bytes {0} [built]
  [45] ./node_modules/loglevel/lib/loglevel.js 7.74 kB {0} [built]
  [46] (webpack)-dev-server/client/socket.js 1.04 kB {0} [built]
  [78] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
  [80] ./node_modules/html-entities/index.js 231 bytes {0} [built]
  [83] (webpack)/hot nonrecursive ^\.\/log$ 170 bytes {0} [built]
  [84] (webpack)/hot/log.js 1.04 kB {0} [optional] [built]
  [85] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [86] ./node_modules/events/events.js 8.33 kB {0} [built]
  [87] ./src/client-app/index.js 1.13 kB {0} [built] [failed] [1 error]
    + 73 hidden modules

ERROR in ./src/client-app/index.js
Module build failed: Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (c:\test-dev3\name_app\node_modules\babel-loader\lib\index.js:1:75)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (c:\test-dev3\name_app\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (c:\test-dev3\name_app\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (c:\test-dev3\name_app\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (c:\test-dev3\name_app\node_modules\webpack\lib\NormalModule.js:182:3)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/client-app/index.js
Child html-webpack-plugin for "..\index.html":
     1 asset
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 1.1 kB {0} [built]
       [1] ./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js 540 kB {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.
```

**Comment by danez** [comment]
It might be that it does not work with npm, not sure why though.

**Comment by dsacramone** [comment]
Did you find a solution, running into this now, too.

**Comment by IoanStoianov** [comment]
This worked for me `npm i @babel/core`

**Comment by kaluogh** [comment]
I have the same problem with rubangarmon . I have install babel-core but doesn't work.need help...

**Comment by kaluogh** [comment]
{
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
              loader: 'babel-loader',
              options: {
                presets: ['@babel/preset-env']
              }
            }
        },

"babel-core": "^6.26.3",
    "babel-loader": "^8.0.0",
    "babel-preset-env": "^1.7.0",

**Comment by danez** [comment]
This should work on the latest master when using yarn, If you have this problem with other packages, please open issues with them.
