### ISSUE TITLE
TypeError: Cannot read property 'visitClass' of undefined at monkeypatch

### ISSUE THREAD

**Issue by chungchiehlun** [reactjs/react-tabs#79]
I just forked the repository. However, when execute `npm test` ,  it failed.
The log out of npm-debu.log listed below.
```log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'test' ]
2 info using npm@2.14.7
3 info using node@v4.2.2
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info pretest react-tabs@0.5.3
6 info test react-tabs@0.5.3
7 verbose unsafe-perm in lifecycle true
8 info react-tabs@0.5.3 Failed to exec test script
9 verbose stack Error: react-tabs@0.5.3 test: `rackt test --single-run --browsers Firefox`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid react-tabs@0.5.3
11 verbose cwd /Users/chiehlun/Project/react/react-tabs
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
14 error node v4.2.2
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error react-tabs@0.5.3 test: `rackt test --single-run --browsers Firefox`
17 error Exit status 1
18 error Failed at the react-tabs@0.5.3 test script 'rackt test --single-run --browsers Firefox'.
18 error This is most likely a problem with the react-tabs package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     rackt test --single-run --browsers Firefox
18 error You can get their info via:
18 error     npm owner ls react-tabs
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by mziwisky** [comment]
i ran into this too.  it's an issue with escope, which is a dependency of babel-eslint, which is a dependency of rackt-cli, which is a dependency of react-tabs (phew!)

i opened a pull request to fix rackt-cli -- https://github.com/mzabriskie/rackt-cli/pull/24

until that goes thru, you can make this temporary change to your local package.json to get tests working again:
```diff
-    "rackt-cli": "^0.5.4",
+    "rackt-cli": "github:mziwisky/rackt-cli",
```

**Comment by chungchiehlun** [comment]
Thanks a lot. :+1:

**Comment by danez** [comment]
With the new updated dependencies this should not be a problem anymore.
